name: Build and Push Docker Image

on:
  push:
    # 同时监听 main 和 test 分支的网页端提交变动
    branches: [ "main", "test" ]
    paths-ignore:
      - 'README.md'
      - 'README_zh.md'  # 如果你未来有中文版说明文档
      - 'LICENSE'       # 顺便忽略开源协议文件的变动
      - 'docker-publish.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # 💡 自动感知分支：main 推送为 latest，test 推送为 test
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/emby-poster:${{ github.ref_name == 'main' && 'latest' || 'test' }}
